/*DICIONARIO DE DADOS*/

USE INFORMATION_SCHEMA;

SHOW TABLES;

DESC TABLE_CONSTRAINTS;

SELECT CONSTRAINT_SCHEMA AS "BANCO",
		 TABLE_NAME AS "TABELA",
		 CONSTRAINT_NAME AS "NOME REGRA", 
		 CONSTRAINT_TYPE AS "TIPO" FROM TABLE_CONSTRAINTS
		 WHERE CONSTRAINT_SCHEMA = 'PROJETO';
		 
/*APAGANDO CONSTRAINTS*/

USE projeto;

ALTER TABLE TELEFONE_CLIENTE
DROP FOREIGN KEY telefone_cliente_ibfk_1;

ALTER TABLE TELEFONE_CLIENTE
ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);