/*CURSORES*/

CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL, 'LEO', 1200, 1650, 2000);
INSERT INTO VENDEDORES VALUES(NULL, 'BIROLIRO', 1400, 1700, 1800);
INSERT INTO VENDEDORES VALUES(NULL, 'TESTE', 1500, 1240, 1250);
INSERT INTO VENDEDORES VALUES(NULL, 'CAZALBÉ', 1300, 1345, 1245);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN+FEV+MAR) AS TOTAL FROM VENDEDORES;

CREATE TABLE VEND_TOTAL(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);
	
	DECLARE REG CURSOR FOR(
		SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
	);
	
	/*VARIAVEL DE MANIPULACAO CONTINUA*/
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	/*JOGA NA MEMÓRIA*/
	OPEN REG;
	
	REPEAT
	
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN
			
			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL / 3;
			
			INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1,VAR2,VAR3, VTOTAL, VMEDIA);
		END IF;
		
	UNTIL FIM END REPEAT;
	
	CLOSE REG;

END
$

DELIMITER ;

SELECT * FROM vendedores;
SELECT * FROM VEND_TOTAL;

CALL INSEREDADOS();

SELECT * FROM VEND_TOTAL;