CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,
	NOME VARCHAR2(100)
);

DROP TABLE TELEFONE;

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY,
	NUMERO VARCHAR2(10)
	ID_FUNCIONARIO INT
);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO;

INSERT INTO FUNCIONARIO VALUES(1,'MAURICIO');
INSERT INTO TELEFONE VALUES(10,'34256545',1);

/*A CONSTRAINT DE INTEGRIDADE REFERENCIAL (FK)
CHECA A INTEGRIDADE LOGO APÓS O COMANDO DE DML
INSERT/ DELETE/ UPDATE - NÃO POSSIBILITANDO ASSIM
A INSERÇÃO DE REGISTROS SEM REFERENCIA */

INSERT INTO TELEFONE VALUES(2, '84558748', 34);

/*VERIFICANDO O ESTADO DAS CONSTRAINTS*/

SELECT CONSTRAINT_NAME, DEFERRABLE, DEFERRED
FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('FUNCIONARIO','TELEFONE');

/*APAGANDO A CONSTRAINT*/

ALTER TABLE TELEFONE DROP CONSTRAINT FK_TELEFONE;

/*RECRIANDO A CONSTRAINT*/

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE
FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO
DEFERRABLE;

INSERT INTO TELEFONE VALUES(4,'44162234', 10);

/*MUDANDO PARA A DTL*/

SET CONSTRAINTS ALL DEFERRED;
INSERT INTO TELEFONE VALUES(4,'44162234', 10);
COMMIT;
--PERMITIRÁ REALIZAR O INSERT SEM VERIFICAR A EXISTENCIA DA CONSTRAINT
--SÓ IRÁ VERIFICAR NO MOMENTO DO COMMIT
