--ALTERANDO O DELIMITADOR DE ';' PARA '$'
DELIMITER $

--DESCOBRINDO O DELIMITADOR
STATUS

--PROC
DELIMITER $

CREATE PROCEDURE CONTA()
BEGIN
	SELECT 10 + 10 AS "CONTA";
END
$

--CHAMANDO PROC(MYSQL)
CALL CONTA()$

DELIMITER ;

DROP PROCEDURE CONTA;
--PROC COM PARAMETRO

DELIMITER $
CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN
	SELECT NUMERO1 + NUMERO2 AS "CONTA";
END
$

DELIMITER ;

CALL CONTA(100,78);
CALL CONTA(1,1);

--PROCEDURES COM TABELA
CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL, 'BANCO DE DADOS FUNDAMENTAL', 25, 200.00);

SELECT * FROM CURSOS

DELIMITER #

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT(3), P_PRECO FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_PRECO);
END 
#

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER', 35, 200.00);

DELIMITER #

CREATE PROCEDURE SEL_CURSO()
BEGIN
	SELECT IDCURSO, NOME, HORAS, VALOR
	FROM CURSOS;
END
#

CALL SEL_CURSO()