CREATE OR REPLACE PROCEDURE BONUS(P_IDALUNO ALUNO.IDALUNO%TYPE, P_PORCENTAGEM NUMBER) -- DINAMICA (ALINHADA COM O TIPO DA COLUNA NA TABELA ALUNO)
AS	
	BEGIN
		UPDATE ALUNO SET SALARIO = SALARIO + (SALARIO * (P_PORCENTAGEM/100))
		WHERE P_IDALUNO = IDALUNO;
	END;
	/
	
CALL BONUS(3,10)