CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY,
	NOME VARCHAR2(30),
	SEXO CHAR(1)
);

INSERT INTO CLIENTE VALUES(1007, 'LEONARDO', 'M');
COMMIT;

SELECT * FROM CLIENTE;

/*CRIANDO A VIEW*/
CREATE OR REPLACE VIEW V_CLIENTE
AS
	SELECT IDCLIENTE, NOME, SEXO 
	FROM 
	CLIENTE;
	
INSERT INTO V_CLIENTE VALUES(1008, 'CLARA', 'F');

SELECT * FROM CLIENTE;
SELECT * FROM V_CLIENTE;

-- QUANDO A VIEW TEM JOIN NÃO CONSIGO REALIZAR O INSERT NA VIEW

CREATE OR REPLACE VIEW V_CLIENTE_RO
AS
	SELECT IDCLIENTE,NOME,SEXO
	FROM CLIENTE
	WITH READ ONLY;
	
-- IMPEDE O COMPARTAMENTO DE INSERÇÃO, SOMENTE LEITURA

--VIEW DE JOIN
CREATE OR REPLACE FORCE VIEW RELATORIO
AS
	SELECT NOME, SEXO, NUMERO
	FROM CLIENTE
	INNER JOIN TELEFONE
	ON IDCLIENTE = ID_CLIENTE;
	
CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY,
	NUMERO VARCHAR2(10),
	ID_CLIENTE INT
);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE;

INSERT INTO TELEFONE VALUES(1,'34459899',1007);
COMMIT;

SELECT * FROM RELATORIO;