/*PROCEDURES*/

USE EMPRESA
GO

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN ('M','F')), --ENUM
	NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO','M', '1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL', 'M', '1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE', 'F', '1979-10-13')

INSERT INTO TELEFONE VALUES('CEL','9879008', 1)
INSERT INTO TELEFONE VALUES('COM','8757909', 1)
INSERT INTO TELEFONE VALUES('CEL','9875890', 2)
INSERT INTO TELEFONE VALUES('CEL','9347689', 2)
INSERT INTO TELEFONE VALUES('CEL','2998689', 3)
INSERT INTO TELEFONE VALUES('CEL','2098978', 2)
INSERT INTO TELEFONE VALUES('CEL','9008679', 3)
GO

/* CRIANDO A PROCEDURE */

CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA
GO

SOMA
EXEC SOMA
GO

/*DINAMICAS - COM PARAMETROS*/

CREATE PROC CONTA @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2 AS RESULTADO
GO

/*EXECUTANDO*/

EXEC CONTA 90,78
GO

/*APAGANDO PROCS*/

DROP PROC CONTA
GO

/*PROCEDURES EM TABELAS*/

SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

/*TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO*/
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TELEFONE
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO

EXEC TELEFONES @TIPO = 'CEL'
GO

EXEC TELEFONES 'COM'
GO

/*PARAMETROS DE OUTPUT*/

SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONE
GROUP BY TIPO
GO

/*PROC COM PARAMETRO DE ENTRADA E PARAMETRO DE SAIDA*/

CREATE PROCEDURE GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
GO

/*EXECUCAO DA PROC COM PARAMETRO DE SAIDA*/

DECLARE @SAIDA INT 
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

/*PROCEDURE DE CADASTRO*/

CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT

	INSERT INTO PESSOA VALUES(@NOME,@SEXO,@NASCIMENTO)

	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)

	INSERT INTO TELEFONE VALUES(@TIPO, @NUMERO, @FK)
GO

EXEC CADASTRO 'LEONARDO', 'M', '1998-06-13', 'CEL', '997882233'
GO

SELECT PESSOA.*, TELEFONE.* 
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
GO