CREATE VIEW V_RELATORIO AS
SELECT C.NOME, C.SEXO,
		IFNULL(C.EMAIL,'SEM EMAIL') AS "E-MAIL",
		T.TIPO,
		T.NUMERO,
		E.BAIRRO,
		E.CIDADE,
		E.ESTADO,
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE

--APOS CRIAR A VIEW
--N É RECOMENDADO POR CAUSA DE PERFORMANCE
--É POSSÍVEL REALIZAR UMA QUERY NA VIEW
SELECT * FROM V_RELATORIO
WHERE SEXO = 'F';

--APAGANDO UMA VIEW
DROP VIEW V_RELATORIO

